### ISSUE TITLE
Scripts not working...

### ISSUE THREAD

**Issue by iamhenry** [almonk/SketchGit#3]
I'm new to github but how do you add a repo to the script? I'd like to create a repo on Github to test it out and branch a few designs from within Sketch.

<del>At the moment running the script it does nothings. I'm using the Beta Version 2.3 (3898). </del>

Thanks

**Comment by almonk** [comment]
Sounds like you need a basic intro to git, check out this link http://hoth.entp.com/output/git_for_designers.html
